[package]
name = "anti_process"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
log = "0.4.14"
native-windows-gui = "1.0.12"
simplelog = "0.11.1"
sysinfo = "0.21.2"
